apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: llm-d-monitoring
spec:
  selector:
    app: grafana
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: grafana-secure
  namespace: llm-d-monitoring
spec:
  to:
    kind: Service
    name: grafana
    weight: 100
  tls:
    termination: edge
  wildcardPolicy: None

